# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gdal_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TIF_TXTEDIT = QtWidgets.QTextEdit(self.centralwidget)
        self.TIF_TXTEDIT.setGeometry(QtCore.QRect(30, 30, 291, 171))
        self.TIF_TXTEDIT.setObjectName("TIF_TXTEDIT")
        self.TIF_TXTEDIT.setFocusPolicy(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 11, 54, 21))
        self.label.setObjectName("label")
        self.SHAPEFILE_TXTEDIT = QtWidgets.QTextEdit(self.centralwidget)
        self.SHAPEFILE_TXTEDIT.setGeometry(QtCore.QRect(400, 30, 281, 171))
        self.SHAPEFILE_TXTEDIT.setObjectName("SHAPEFILE_TXTEDIT")
        self.SHAPEFILE_TXTEDIT.setFocusPolicy(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 111, 23))
        self.label_2.setObjectName("label_2")
        self.OPEN_SAVE_BN = QtWidgets.QPushButton(self.centralwidget)
        self.OPEN_SAVE_BN.setGeometry(QtCore.QRect(280, 460, 75, 23))
        self.OPEN_SAVE_BN.setObjectName("OPEN_SAVE_BN")

        self.RUN_CLIP_BN = QtWidgets.QPushButton(self.centralwidget)
        self.RUN_CLIP_BN.setGeometry(QtCore.QRect(400, 460, 75, 23))
        self.RUN_CLIP_BN.setObjectName("RUN_CLIP_BN")
        self.RUN_MASK_BN = QtWidgets.QPushButton(self.centralwidget)
        self.RUN_MASK_BN.setGeometry(QtCore.QRect(485, 460, 75, 23))
        self.RUN_MASK_BN.setObjectName("RUN_MASK_BN")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 460, 61, 23))
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 230, 241, 130))
        self.widget.setObjectName("widget")
        self.CLIP_SIZE_LINEEDIT = QtWidgets.QLineEdit(self.widget)
        self.CLIP_SIZE_LINEEDIT.setGeometry(QtCore.QRect(80, 70, 113, 23))
        self.CLIP_SIZE_LINEEDIT.setObjectName("CLIP_SIZE_LINEEDIT")
        self.CLIP_TYPE_COMBOX = QtWidgets.QComboBox(self.widget)
        self.CLIP_TYPE_COMBOX.setGeometry(QtCore.QRect(80, 40, 111, 23))
        self.CLIP_TYPE_COMBOX.setObjectName("CLIP_TYPE_COMBOX")

        self.CLIP_FDNAME_COMBOX = QtWidgets.QComboBox(self.widget)
        self.CLIP_FDNAME_COMBOX.setGeometry(QtCore.QRect(80, 100, 111, 23))
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 330, 61, 23))

        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 71, 23))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 23))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 71, 23))
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(30, 360, 241, 80))
        self.widget_2.setObjectName("widget_2")
        self.MASK_LABEL_LINEEDIT = QtWidgets.QLineEdit(self.widget_2)
        self.MASK_LABEL_LINEEDIT.setGeometry(QtCore.QRect(80, 40, 113, 23))
        self.MASK_LABEL_LINEEDIT.setObjectName("MASK_LABEL_LINEEDIT")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 71, 23))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 71, 23))
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(280, 230, 500, 111))
        self.widget_3.setObjectName("widget_3")
        self.GEOREFED_LINEEDIT = QtWidgets.QLineEdit(self.widget_3)
        self.GEOREFED_LINEEDIT.setGeometry(QtCore.QRect(175, 40, 220, 23))
        self.GEOREFED_LINEEDIT.setObjectName("GEOREFED_LINEEDIT")
        self.GEOREFED_LINEEDIT.setFocusPolicy(False)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 140, 23))
        self.label_7.setObjectName("label_7")
        self.OPEN_GEOREFED_BN = QtWidgets.QPushButton(self.widget_3)
        self.OPEN_GEOREFED_BN.setGeometry(QtCore.QRect(400, 40, 75, 23))
        self.OPEN_GEOREFED_BN.setObjectName("OPEN_GEOREFED_BN")
        self.OPEN_MASK_BN = QtWidgets.QPushButton(self.widget_3)
        self.OPEN_MASK_BN.setGeometry(QtCore.QRect(400, 70, 75, 23))
        self.OPEN_MASK_BN.setObjectName("UNGEOREFED_BN")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 170, 23))
        self.label_9.setObjectName("label_9")
        self.UNGEOREFED_LINEEDIT = QtWidgets.QLineEdit(self.widget_3)
        self.UNGEOREFED_LINEEDIT.setGeometry(QtCore.QRect(175, 70, 220, 23))
        self.UNGEOREFED_LINEEDIT.setObjectName("UNGEOREFED_LINEEDIT")
        self.UNGEOREFED_LINEEDIT.setFocusPolicy(False)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 91, 23))
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(290, 360, 500, 80))
        self.widget_4.setObjectName("widget_4")
        self.MERGE_LINEEDIT = QtWidgets.QLineEdit(self.widget_4)
        self.MERGE_LINEEDIT.setGeometry(QtCore.QRect(165, 40, 220, 23))
        self.MERGE_LINEEDIT.setObjectName("MERGE_LINEEDIT")
        self.MERGE_LINEEDIT.setFocusPolicy(False)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 140, 23))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 54, 23))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.OPEN_MERGE_BN = QtWidgets.QPushButton(self.widget_4)
        self.OPEN_MERGE_BN.setGeometry(QtCore.QRect(390, 40, 75, 23))
        self.OPEN_MERGE_BN.setObjectName("OPEN_MERGE_BN")
        self.SAVE_PATH_DIR_LINEEDIT = QtWidgets.QLineEdit(self.centralwidget)
        self.SAVE_PATH_DIR_LINEEDIT.setGeometry(QtCore.QRect(110, 460, 161, 23))
        self.SAVE_PATH_DIR_LINEEDIT.setObjectName("SAVE_PATH_DIR_LINEEDIT")
        self.SAVE_PATH_DIR_LINEEDIT.setFocusPolicy(False)
        self.RUN_REF_BN = QtWidgets.QPushButton(self.centralwidget)
        self.RUN_REF_BN.setGeometry(QtCore.QRect(570, 460, 100, 23))
        self.RUN_REF_BN.setObjectName("RUN_REF_BN")
        self.RUN_MERGE_BN = QtWidgets.QPushButton(self.centralwidget)
        self.RUN_MERGE_BN.setGeometry(QtCore.QRect(680, 460, 75, 23))
        self.RUN_MERGE_BN.setObjectName("RUN_MERGE_BN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.OPEN_TIF_ACTION = QtWidgets.QAction(MainWindow)
        self.OPEN_TIF_ACTION.setObjectName("OPEN_TIF_ACTION")
        self.OPEN_SHAPEFILE_ACTION = QtWidgets.QAction(MainWindow)
        self.OPEN_SHAPEFILE_ACTION.setObjectName("OPEN_SHAPEFILE_ACTION")
        self.menu.addAction(self.OPEN_TIF_ACTION)
        self.menu.addAction(self.OPEN_SHAPEFILE_ACTION)
        self.menubar.addAction(self.menu.menuAction())
        self.PROCESS_BAR = QtWidgets.QProgressBar(self)
        self.PROCESS_BAR.setGeometry(110, 530, 600, 25)
        self.PROCESS_BAR.setRange(0, 100)


        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 505, 70, 23))
        self.label_14.setObjectName("label")

        self.retranslateUi(MainWindow)
        self.CLIP_TYPE_COMBOX.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GeoTool"))
        self.setWindowIcon(QIcon('src/ico/title.png'))
        self.label.setText(_translate("MainWindow", "TIF信息"))
        self.label_2.setText(_translate("MainWindow", "shapefile信息"))
        self.RUN_CLIP_BN.setText(_translate("MainWindow", "裁剪"))
        self.RUN_MASK_BN.setText(_translate("MainWindow", "掩膜"))
        self.label_6.setText(_translate("MainWindow", "保存位置"))
        self.CLIP_TYPE_COMBOX.setCurrentText(_translate("MainWindow", "格网裁剪"))
        self.label_3.setText(_translate("MainWindow", "裁剪类型"))
        self.label_4.setText(_translate("MainWindow", "格网大小"))
        self.label_8.setText(_translate("MainWindow", "裁剪"))
        self.label_5.setText(_translate("MainWindow", "掩膜数值"))
        self.label_10.setText(_translate("MainWindow", "掩膜"))
        self.label_7.setText(_translate("MainWindow", "剪裁位置(有坐标系)"))
        self.OPEN_GEOREFED_BN.setText(_translate("MainWindow", "打开"))
        self.OPEN_MASK_BN.setText(_translate("MainWindow", "打开"))
        self.label_15.setText(_translate("MainWindow", "shp字段"))
        self.label_9.setText(_translate("MainWindow", "分类结果位置(无坐标系)"))
        self.label_11.setText(_translate("MainWindow", "定义坐标系"))
        self.label_12.setText(_translate("MainWindow", "TIF位置(有坐标系)"))
        self.label_13.setText(_translate("MainWindow", "合并"))
        self.label_14.setText(_translate("MainWindow", "处理进度"))
        self.OPEN_MERGE_BN.setText(_translate("MainWindow", "打开"))
        self.RUN_REF_BN.setText(_translate("MainWindow", "定义坐标系"))
        self.OPEN_SAVE_BN.setText(_translate("MainWindow", "打开"))
        self.RUN_MERGE_BN.setText(_translate("MainWindow", "合并"))
        self.menu.setTitle(_translate("MainWindow", "打开"))
        self.OPEN_TIF_ACTION.setText(_translate("MainWindow", "打开TIF文件"))
        self.OPEN_SHAPEFILE_ACTION.setText(_translate("MainWindow", "打开Shapefile文件"))

